version: "2.1"
orbs:
  codecov: codecov/codecov@4.0.1
jobs:
  build:
    docker:
      - image: cimg/node:21.7.3
    steps:
      - checkout
      - run:
          name: remove node_modules
          command: rm -rf node_modules/
      - run:
          name: install dependences
          command: npm install
      - run:
          name: run code lint
          command: npm run lint
      - run:
          name: run test
          command: npm run test
      - codecov/upload:
